import type { Core } from "../../../core/index.ts";
import { fnv1aHex, worldToJson } from "./json.ts";
import type { HostInspect, KitFileMap, PluginKit } from "../types.ts";

export const KIT_LUME_FORMAT = 2;

export const KNOWN_EVENTS = [
  "lume:project-compiled",
  "lume:game-created",
  "lume:game-beat",
  "lume:entity-interact",
  "lume:project-saved",
  "lume:project-loaded",
  "lume:project-deleted",
  "lume:playtest-saved",
  "lume:playtest-loaded",
  "lume:user-edited-source",
  "lume:user-clicked-play",
  "lume:user-clicked-rewind",
  "lume:game-error",
  "lume:world-event",
  "lume:knowledge-updated",
  "lume:intent-dispatched",
  "lume:story-sifted",
  "lume:ext-plugin",
] as const;

export const DENIED_METHODS = ["getStore", "registerComponent", "getComponent", "register"] as const;

const EXAMPLE_SOURCE = `// ext-hello — plugin externo Lume (sandbox)
// activate / deactivate recebem o host. Sem import, sem DOM, sem núcleo.

var manifest = {
  name: "ext-hello",
  version: "1.0.0",
  description: "Exemplo gerado pelo kit. Só lê o mundo e escreve logs."
};

function activate(host) {
  host.log("ext-hello activo. capabilities=" + host.inspect().capabilities.map(function (c) { return c.name; }).join(","));
  host.on("lume:game-beat", function () {
    host.log("beat");
  });
}

function deactivate() {}
`;

function stableStringify(value: unknown): string {
  return JSON.stringify(value, null, 2) + "\n";
}

export function fingerprintFiles(files: KitFileMap): string {
  const parts: string[] = [];
  for (const path of Object.keys(files).sort()) {
    if (path === "FINGERPRINT") continue;
    parts.push(path, String(files[path]!.length), files[path]!);
  }
  return fnv1aHex(parts.join("\n"));
}

export function renderKit(inspect: HostInspect, formatVersion: number = KIT_LUME_FORMAT): PluginKit {
  const snapshot = {
    format: 1,
    lumeFormatVersion: formatVersion,
    generatedBy: "lume-website",
    plugins: inspect.plugins,
    capabilities: inspect.capabilities,
    events: inspect.events,
    deniedMethods: [...DENIED_METHODS],
    host: {
      inspect: "() => HostInspect",
      call: "(capability, method, ...jsonArgs) => json",
      on: "(eventType, handler) => void",
      emit: "(topic, payload) => void  // wraps lume:ext-plugin",
      log: "(message) => void",
      storage: "{ get, set, remove }  // isolated per ext-* plugin",
    },
    rules: [
      "name MUST match /^ext-[a-z0-9-]+$/",
      "never lume-* (kernel plugins)",
      "no import / fetch / DOM / Function / eval",
      "call() JSON only; getStore and registerComponent are denied",
      "mutations go through NarrativeEngine.interact or IntentEngine — never patch the kernel",
      "guest capabilities live in ExtHost, not Core.capabilityRegistry",
    ],
    glossary: {
      Entity: "tags + stats + links + extra (not ECS Component)",
      Rule: "ON / IF / DO + narrativa",
      Intent: "intent.* command or DO: INTENT",
      EventDiegetic: "DO: EMIT → entity tags:event",
      EventPlatform: "lume:* TypedEvent",
      Plugin: "lume-* first-party | ext-* guest",
    },
    language: {
      entities: "ID.{ tags: agent; stats: hp=10; links: current_location=SALA; }",
      rules: "ON: PORTA\\nIF: JOGADOR.intent=open\\nDO: PORTA.aberta\\nnarrativa: \\\"A porta abre.\\\"",
      intent: "intent.action.interact.take.TOCHA",
      doVerbs: ["tag/stat/link", "CREATE", "DESTROY", "EMIT", "KNOW", "INTENT"],
    },
  };

  const capUnion = inspect.capabilities.map((c) => JSON.stringify(c.name)).join(" | ") || "string";
  const hostDts = `/** Generated by the Lume website from the live kernel. Do not edit by hand. */
export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
export type JsonEntity = { id: string; tags: string[]; stats: Record<string, number>; links: Record<string, string>; extra?: Record<string, string> };
export type HostInspect = {
  plugins: { name: string; version: string; provides: { name: string; version: string }[] }[];
  capabilities: { name: string; version: string; provider: string; methods: string[] }[];
  events: string[];
  world: JsonEntity[] | null;
};
export type SandboxHost = {
  readonly pluginName: string;
  log(message: string): void;
  inspect(): HostInspect;
  call(capability: ${capUnion}, method: string, ...args: Json[]): Json;
  on(eventType: string, handler: (payload: Json) => void): void;
  emit(topic: string, payload?: Json): void;
  storage: { get(key: string): string | null; set(key: string, value: string): void; remove(key: string): void };
};
export declare function activate(host: SandboxHost): void;
export declare function deactivate(): void;
`;

  const agents = `# AGENTS — plugin externo Lume

Este zip foi gerado pelo **website** a partir do kernel vivo (capabilities, métodos, eventos).
Não foi escrito por uma IA. Se o Lume ganhar um plugin/capability novo, descarrega o kit outra vez.

## O que produzir
Um ficheiro \`plugin.js\` (ou JSON \`{ "manifest", "source" }\`) com:

- \`manifest.name\` a começar por \`ext-\` (ex: \`ext-weather\`)
- \`function activate(host) { ... }\`
- opcional \`function deactivate() {}\`

Carregar no Lume: Configuração → Plugins externos.

## Host (sandbox)
${inspect.capabilities.map((c) => `- call(${JSON.stringify(c.name)}, method, ...args) methods: ${c.methods.join(", ") || "(none)"}`).join("\n")}

Métodos recusados: ${DENIED_METHODS.join(", ")}.

## Idioma (não Elm, não ECS)
- Entity = tags/stats/links, não Component
- Rule = ON/IF/DO, não Law
- Intent = intent.action… ou DO: INTENT
- Evento diegético = DO: EMIT; plataforma = lume:*

## Não fazer
- Não importar o núcleo, não patchar findMatchingRule
- Não usar o prefixo lume-
- Não aceder a DOM / fetch / Function / eval
- Mutação só via call('NarrativeEngine', …) ou IntentEngine — JSON clone; o kernel não é o teu objeto
`;

  const readme = `# Lume external plugin kit

lume formatVersion: ${formatVersion}

1. Lê AGENTS.md (instruções para a IA que vai escrever o plugin).
2. Copia examples/ext-hello/plugin.js e muda o nome para ext-<algo>.
3. No Lume: Ajuda → Descarregar kit de plugins externos.

O snapshot host.json é a fonte de verdade das capabilities neste instante do website.
`;

  const files: KitFileMap = {
    "README.md": readme,
    "AGENTS.md": agents,
    "host.json": stableStringify(snapshot),
    "host.d.ts": hostDts.endsWith("\n") ? hostDts : `${hostDts}\n`,
    "examples/ext-hello/plugin.js": EXAMPLE_SOURCE.endsWith("\n") ? EXAMPLE_SOURCE : `${EXAMPLE_SOURCE}\n`,
    "examples/ext-hello/plugin.json": stableStringify({
      manifest: { name: "ext-hello", version: "1.0.0", description: "Exemplo gerado pelo kit." },
      source: EXAMPLE_SOURCE,
    }),
  };
  const fingerprint = fingerprintFiles(files);
  files.FINGERPRINT = `${fingerprint}\n`;
  return {
    fingerprint,
    files,
    filename: `lume-plugin-kit-${fingerprint}.zip`,
  };
}

export function inspectFromCore(core: Core): HostInspect {
  const diagnostics = core.getDiagnostics();
  const capabilities = diagnostics.capabilities
    .map((cap) => ({
      name: cap.name,
      version: cap.version,
      provider: cap.provider,
      methods: Object.keys(cap.api ?? {})
        .filter((method) => !DENIED_METHODS.includes(method as (typeof DENIED_METHODS)[number]))
        .sort(),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
  const plugins = core
    .listPlugins()
    .map((manifest) => ({
      name: manifest.name,
      version: manifest.version,
      provides: [...(manifest.capabilities?.provides ?? [])].sort((a, b) => a.name.localeCompare(b.name)),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
  let world = null;
  try {
    const ide = core.getService<{ getState: () => { game?: { worldModel?: Map<string, unknown> } | null } }>("IdeState");
    const model = ide.getState().game?.worldModel;
    world = model instanceof Map ? worldToJson(model) : null;
  } catch {
    world = null;
  }
  return { plugins, capabilities, events: [...KNOWN_EVENTS], world };
}
